CS3203-Team-6/SPA

Code/SPA/SPA.vcxproj, Code/UnitTesting/UnitTesting.vcxproj
Accept Merge Request to resolve all errors with visual studio filter files.
=> Iteration 1.4 : Fix Spa and UnitTesting vcxproj filters

Code/UnitTesting/PreprocesserTest.cpp, Code/source/ElseParser.cpp, Code/source/FollowStorage.cpp, Code/source/IfParser.cpp, Code/source/ModifyStorage.cpp, Code/source/PKB.cpp, Code/source/ParentStorage.cpp, Code/source/Preprocesser.cpp, Code/source/Preprocesser.h, Code/source/QueryParser.cpp, Code/source/UseStorage.cpp, Code/source/WhileParser.cpp, Tests/source1.txt, Tests/source2.txt, Tests/source3.txt
apparently all static members must be defined and initialized outside of the class definition
close #52
=> Fixed LNC2001 error during build

Code/source/PostProcessor.cpp
=> Initialized static member

Code/AutoTester/source/TestWrapper.cpp, Code/UnitTesting/QueryEvaluatorTest.cpp, Code/source/QueryEvaluator.cpp, Code/source/QueryEvaluator.h, Code/source/QueryParser.cpp, Code/source/QueryParser.h
=> Change return type of PQL evaluator to unordered_set

Code/source/ModifyStorage.cpp, Code/source/ModifyStorage.h, Code/source/PKB.cpp, Code/source/PKB.h, Code/source/UseStorage.cpp
Changed return value of getVarModifiedBy(int stm)/getVarModifiedBy(string proc) from string to unordered_set<string>
Changed addModifies to add the variable into a list of variables.
Fixed bug where UseStorage and ModifyStorage attempts to add a new list of variables instead adding a variable into an existing list
=> Changed return value 

Code/source/PKB.cpp, Code/source/PKB.h
The method returns all pairs of assign statement & variable that has a right side expression that matches the pattern string given. 
For clauses such as pattern a( var, _"a+b"_)
isExclusive is a bool to tell if the expression is match exclusively to the given string without any characters on either side.
e.g. findPatternPairs( "", true) would search for an expression that is an empty string
findPatternPairs("", false) on the other would search any expression that has "" as a substring, which all expressions.
This goes for findPattern as well
=> created a method findPatternPairs

Code/source/QueryEvaluator.cpp, Code/source/QueryParser.cpp
fix modifies and uses conditions
=> Query Validation & Evaluation Fixes

Code/Tests/queries3.txt, Code/Tests/source3.txt
Add queries3.txt and update source3.txt to include:
- nested while loops
- longer assignment statements
- more complex while condition
- irregular whitespaces
=> Add System Test

Code/AutoTester/source/TestWrapper.cpp, Code/SPA/SPA.vcxproj.filters, Code/Tests/queries1.txt, Code/source/DesignExtractor.cpp, Code/source/ExpressionUtil.cpp, Code/source/ExpressionUtil.h, Code/source/ReadParser.cpp
1) Fixed a bug in Design Extractor
2) Added 8 simple queries to query1.txt testing Follow* and Parent*
=> Fix Design Extractor Logic and Added new Queries to query1.txt

Code/Tests/queries3.txt
Fix an error displaying test cases when & is in comments
=> Fix an error in queries3.txt

Code/Tests/queries2.txt, Code/source/DesignExtractor.cpp
Made a Fix to Parent* not populating properly
=> Fix Parent* Logic in DesignExtractor

Code/Tests/queries3.txt
Made some errors in the query result previously
=> Fix wrong queries

Code/Tests/irregular-queries1.txt, Code/Tests/queries4.txt, Code/UnitTesting/QueryParserTest.cpp, Code/source/QueryParser.cpp
Resolve #109 & bug in iteration 1
=> Fix pattern clause validation

Code/SPA/SPA.vcxproj, Code/SPA/SPA.vcxproj.filters, Code/UnitTesting/QueryParserTest.cpp, Code/UnitTesting/QueryValidatorTest.cpp, Code/UnitTesting/UnitTesting.vcxproj, Code/UnitTesting/UnitTesting.vcxproj.filters, Code/source/QueryParser.cpp, Code/source/QueryParser.h, Code/source/QueryValidator.cpp, Code/source/QueryValidator.h, Code/source/StringUtil.cpp, Code/source/StringUtil.h
- separate QueryParser and QueryValidator to follow separation of concerns
- add functions to stringUtil and delete unnecessary functions
- reorder and write comments on such that clause validation logic
=> Update code style

Code/Tests/irregular-queries1.txt, Code/Tests/queries1.txt, Code/UnitTesting/QueryParserTest.cpp, Code/UnitTesting/QueryValidatorTest.cpp, Code/source/QueryParser.cpp, Code/source/QueryValidator.cpp
new features:
- supports new declaration type: prog_line
- supports select boolean and tuples
- supports new relations in such that clause: Calls, Calls*, Next, Next*, Affect, Affect*
- supports new designEntity in pattern clause: pattern while & if
tests:
- unit tests
- system tests for select boolean, select tuples, new relations in such that clause (Calls, Calls*, Next, Next*, Affect, Affect*)
to be implemented in next sub-iteration:
- 'with' clause
- multiple such that and pattern condition
=> PQL Parser & Validator: Iteration 2.1

Code/AutoTester/source/TestWrapper.cpp, Code/SPA/SPA.vcxproj, Code/SPA/SPA.vcxproj.filters, Code/UnitTesting/AssignParserTest.cpp, Code/UnitTesting/ExpressionUtilTest.cpp, Code/source/AssignParser.cpp, Code/source/AssignParser.h, Code/source/CallParser.cpp, Code/source/CallParser.h, Code/source/DesignExtractor.cpp, Code/source/DesignExtractor.h, Code/source/ElseParser.cpp, Code/source/ElseParser.h, Code/source/ExpressionUtil.cpp, Code/source/ExpressionUtil.h, Code/source/IfParser.cpp, Code/source/IfParser.h, Code/source/LexicalToken.cpp, Code/source/LexicalToken.h, Code/source/PKB.h, Code/source/Parser.cpp, Code/source/Parser.h, Code/source/PrintParser.cpp, Code/source/PrintParser.h, Code/source/ProcedureParser.cpp, Code/source/ProcedureParser.h, Code/source/ReadParser.cpp, Code/source/ReadParser.h, Code/source/WhileParser.cpp, Code/source/WhileParser.h
1) Added Call Logic to parser
2) Added CallParser to Parse Call Statement
3) Reduced Namespace Pollution that was discussed in Iteration 1.
=> Iteration 2: Call Logic

Code/UnitTesting/QueryParserTest.cpp, Code/UnitTesting/QueryValidatorTest.cpp, Code/source/QueryParser.cpp, Code/source/QueryParser.h, Code/source/QueryValidator.cpp, Code/source/QueryValidator.h
- parse and validate multiple condition in queries
- parse and validate "with" clause
=> Multiple condition & "with" clause

Code/SPA/SPA.vcxproj, Code/SPA/SPA.vcxproj.filters, Code/source/CallStorage.cpp, Code/source/CallStorage.h, Code/source/NextStorage.cpp, Code/source/NextStorage.h, Code/source/PKB.cpp, Code/source/PKB.h
Created CallStorage and NextStorage
Added PKB methods for Call/Call* and Next/Next*
=> Call/Call* and Next

Code/source/DesignExtractor.cpp
=> Iter 2 bug fix

Code/AutoTester/source/TestWrapper.cpp, Code/source/DesignExtractor.cpp, Code/source/Parser.cpp, Tests/invalid-SIMPLE-cyclic-test/source-CyclicCall.txt, Tests/invalid-SIMPLE-duplicateprocedure/source-DuplicateProcedure.txt, Tests/invalid-SIMPLE-non-existantcall/source-NonExistantProc.txt
Added 3 Invalid SIMPLE sources with semantic errors.
Allow Parser to detect if Duplicate Procedure
Fix an Error in DE DFSrecursive.
=> Iteration 2: Invalid SIMPLE sources.

Code/source/ControlVariableStorage.cpp, Code/source/ControlVariableStorage.h, Code/source/PKB.cpp, Code/source/PKB.h
hasIfStm changed to return all IfStms With Control Variables.
=> Iteration 2 : PKB Changes to accomodate PQL.

Tests/system-tests-1/Multiple-easy.txt
=> Multiple conditions queries - easy

.gitignore, Code/source/QueryParser.cpp, Tests/system-tests-1/WithClause.txt, Tests/system-tests-1/runAllQueries.bat, Tests/system-tests-2/Calls.txt, Tests/system-tests-2/CallsStar.txt
Update source 1 queries file:
- WithClause
Add batch file to run all the queries in source 1
Queries for source 2 for the following relations:
- Calls
- Calls*
=> Source 2 testcases

Code/IntegrationTesting/DesignExtractorPKBTest.cpp, Code/UnitTesting/Utility/ExpressionUtilTest.cpp, Code/source/ExpressionUtil.cpp, Code/source/Parser.cpp, Code/source/RunTimeDesignExtractor.cpp, Code/source/RunTimeDesignExtractor.h
1. Fix a bug in Affects(SYN,SYN) population where in awhile loop merging was not happening
2. Fix a bug in ExpressionUtil where in Expresions such as ( (x+t) ), spaces between brackets was not being parsed
3. Fix a bug in Follows where Follows(0, 0) was being inserted.
4. Implemented isAffectStar(INTEGER,INTEGER) for Affects(INTEGER,INTEGER).
=> Iteration 3 Fixes

Code/UnitTesting/PQL/OptimizerTest.cpp, Code/UnitTesting/Utility/OptimizerUtilityTest.cpp, Code/source/Optimizer.cpp, Code/source/Optimizer.h, Code/source/OptimizerUtility.cpp, Code/source/OptimizerUtility.h, Tests/system-tests-2/Parent.txt, Tests/system-tests-2/ParentStar.txt
Optimizer:
- Bugfixes for unit tests
- added non-synonym
- added comments for readability
System test files:
- Parent
- Parent*
=> Optimizer + sys test query file

Code/source/SuchThatEvaluator.cpp, Tests/system-tests-1/Boolean.txt, Tests/system-tests-1/Modifies.txt, Tests/system-tests-4/AffectsStar.txt, Tests/system-tests-4/runAllQueries.bat
=> Add system test queries
